# Dataset Configuration
path: Detecting-the-PCB-object-3
train: train/images
val: valid/images
test: test/images

# Classes
nc: 21
names:
  - battery
  - button
  - buzzer
  - capacitor
  - clock
  - connector
  - diode
  - display
  - fuse
  - heatsink
  - ic
  - inductor
  - led
  - pads
  - pins
  - potentiometer
  - relay
  - resistor
  - switch
  - transformer
  - transistor
